
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # keep in sync with ruff== in pyproject.toml [testenv:format]
    rev: v0.16.9
    hooks:
    -   id: ruff-check
        args: [--fix]
        files: ^(src|tests)/
    -   id: ruff-format
        files: ^(src|tests)/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
    -   id: codespell
        args: [src/]
        pass_filenames: false
        additional_dependencies: [tomli]
